version: "3.3"

services:
    recorder:
        build: recorder
        restart: always
        volumes:
            - ./video:/video
        environment:
            TZ: Europe/Samara
    processor:
        build: processor
        restart: always
        volumes:
            - ./video:/video
        ports:
            - 9000:80
        environment:
            TZ: Europe/Samara
