openapi: 3.0.3
info:
  title: Camera backend
  description: |-
    Camera event processor. [Project repository](https://github.com/vicanis/camrec3)
  version: 1.0.0
tags:
  - name: camera
    description: Everything about camera
paths:
  /play/{timestamp}:
    get:
      tags:
        - camera
      summary: Render player page
      parameters:
        - name: timestamp
          description: Get video from this point of time. Date format `YYYYMMDDhhmmss`
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Timestamp"
      responses:
        200:
          description: Successful operation
          content:
            text/html:
              schema:
                type: string
  /event/{timestamp}:
    get:
      tags:
        - camera
      summary: Get event video file
      parameters:
        - name: start
          in: path
          required: true
          description: Get video from this point of time. Date format `YYYYMMDDhhmmss`
          schema:
            $ref: "#/components/schemas/Timestamp"
        - name: duration
          in: query
          description: Video duration in seconds
          schema:
            type: string
            example: 30
            default: 30
      responses:
        200:
          description: Successful operation
          content:
            video/mp4:
              schema:
                $ref: "#/components/schemas/Binary"
        400:
          description: No timestamp, timestamp parse failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Video not found. No response body
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /frame/{timestamp}:
    get:
      tags:
        - camera
      summary: "Take a picture from the given timestamp"
      parameters:
        - name: timestamp
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Timestamp"
      responses:
        200:
          description: Successful operation
          content:
            image/jpeg:
              schema:
                $ref: "#/components/schemas/Binary"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: "error occurred"
    Binary:
      type: string
      format: binary
      example: "<binary>"
    Timestamp:
      type: string
      pattern: '^\d{14}$'
      example: 20060102150405
      description: Format `YYYYMMDDhhmmss`
