AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
    mailhandler:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main
            Runtime: go1.x
            CodeUri: mailhandler/.
            Description: Handle hicloud email
            Timeout: 5
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSLambda_ReadOnlyAccess
                - AWSXrayWriteOnlyAccess
            Tracing: Active
    eventprocessor:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main
            Runtime: go1.x
            CodeUri: eventprocessor/.
            Description: Handle event list
            Timeout: 5
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSLambda_ReadOnlyAccess
                - AWSXrayWriteOnlyAccess
            Tracing: Active
    dashboard:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main
            Runtime: go1.x
            CodeUri: dashboard/.
            Description: Handle dashboard requests
            Timeout: 5
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSLambda_ReadOnlyAccess
                - AWSXrayWriteOnlyAccess
            Tracing: Active
